import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

shell = "fish"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
offset = { x = -1, y = 0 }
size = 11

[window]
opacity = 0.75
padding = { x = 10, y = 0 }
startup_mode = "Maximized"